### ISSUE TITLE
Residential Lilac Release Epic

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#253]
### Cherry-picks
- [x] #254 Rapid Response 
- [x] #255 Remote Gradebook & Canvas
- [x] #263 We need to cherry-pick PR https://github.com/edx/edx-platform/pull/27252 into our mitx/lilac branch, or persuade edX to cherry-pick it into the Lilac.2 release

### Upstream PRs
- [x] https://github.com/mitodl/edx-platform/issues/135 Upstream "make default value of invite_only configurable"
- [ ] Decide what to do about CAPA report bug (https://github.com/mitodl/edx-platform/pull/240 and https://github.com/mitodl/edx-platform/pull/239)
- [x] ~~https://github.com/edx/edx-platform/pull/26760 making LOGIN_REDIRECT_WHITELIST configurable through env files~~ (not a Residential requirement)

### Plugin updates 
- [x] https://github.com/mitodl/edx-sysadmin/issues/16 permissions
- [x] https://github.com/mitodl/edx-sysadmin/issues/15 (or implement a git web hook API)

### Theme changes
- [x] https://github.com/mitodl/mitx-theme/pull/132

### Issues from MITx team
- [x] [Spring 21 #11](https://github.mit.edu/mitx/Spring-2021/issues/11) Some Emails Have edX Styles
- [ ] [Spring 21 #4](https://github.mit.edu/mitx/Spring-2021/issues/4) "+New Unit" Feature Within Other Units in Studio Broken (duplicate of https://github.com/mitodl/edx-platform/issues/230) 
- [ ] https://github.com/mitodl/edx-platform/issues/267 Lilac: Error on file upload in Studio (intermittent)

**Comment by pdpinch** [comment]
This epic is done, be definition. Even though some of the issue linger on.
