### ISSUE TITLE
refactor the sysadmin dashboard as a pluggable Django app

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-platform#96]
edX now supports pluggable django apps that can have dependencies on edx-platform. It would be more convenient to managed the sysadmin dashboard as a separate, optionally-installed app.

┆Issue is synchronized with this [Trello card](https://trello.com/c/nYLHwPAe) by [Unito](https://www.unito.io/learn-more)

**Comment by pdpinch** [comment]
In particular, Dave asked that we store things like gitlogs in the app's own storage instead of in mongo -- they might want to get rid of mongo some day.

**Comment by pdpinch** [comment]
The existing functionality of the sysadmin panel is documented in an ADR at https://github.com/edx/edx-platform/blob/master/lms/djangoapps/dashboard/decisions/0001-sysadmin-dashboard.rst

There is some discussion of the subset of features that would be needed in the new, pluggable version, at https://github.com/edx/edx-platform/pull/24048

edX has a short guide on how to create a pluggable django app: https://openedx.atlassian.net/wiki/spaces/AC/pages/30965856/How+to+add+a+new+feature+to+LMS+or+Studio#HowtoaddanewfeaturetoLMSorStudio-django-app-separate-repoHowtoaddanewDjangoappinitsownGitrepository

We have done this before for https://github.com/mitodl/edx-git-auto-export and, I think, https://github.com/mitodl/rapid-response-xblock

**Comment by asadiqbal08** [comment]
Here is the SysAdmin checklist that would be helpful for further in-depth discussions about application demand. 

### SysAdmin Checklist

- [ ] Creation of external django App "SysAdmin" (Persisting the current UI same as in OpenEdx). mostly as did in past for https://github.com/mitodl/edx-git-auto-export. App will request specifically and get JSON responses.
     - [ ] UI Templates (remain consistent) 
     - [ ] A valid documentation for integrating/installation with openEdx.
     - [ ] Unit Tests

- [ ] Need to introduce an entry point for communication in edx-platform that will host the API's (CRUD Operations). The API's will be used by our external django SysAdmin application. I am bit new to OpenEdx [Django App Plugins](https://github.com/edx/edx-django-utils/tree/master/edx_django_utils/plugins#django-app-plugins) but seems it would be an option because plugins just required some minimal configuration changes in edx-platform otherwise introduction of a Django app for hosting `lms/djangoapps/dashboard/sysadmin.py` operations under [/openedx/features/djangoapps](https://openedx.atlassian.net/wiki/spaces/AC/pages/30965856/How+to+add+a+new+feature+to+LMS+or+Studio#HowtoaddanewfeaturetoLMSorStudio-django-app-separate-repoHowtoaddanewDjangoappinitsownGitrepository) as something implemented for [Course Enrollments](https://github.com/edx/edx-platform/tree/master/openedx/core/djangoapps/enrollments) in edx-platform.

- [ ] Required to define a set of API's endpoints under SysAdmin plugin app. Following Endpoints (as @pdpinch suggested in a Draft PR):

- [ ] [Create user accounts (REST API)](https://github.com/edx/edx-platform/blob/50dd1238408dc6785f022d8540961f96e0d6bb4f/lms/djangoapps/dashboard/sysadmin.py#L113-L151) 
    - [ ] One can take advantage from `/user/v1/validation/registration` endpoint to get validation decision. [RegistrationValidationView](https://github.com/mitodl/edx-platform/blob/master/openedx/core/djangoapps/user_authn/views/register.py#L579)
      ```
            Get validation information about user data during registration.
            Client-side may request validation for any number of form fields,
            and the API will return a conclusion from its analysis for each
            input
      ```
     - [ ] `POST Params`: username, fullname and password.
     - [ ]  `Permissions`: Staff
     - [ ] `Unit testing`: 100% coverage
       ##### NOTE: I can see, a [helper method](https://github.com/edx/edx-platform/blob/b6dbbb6f838d57d1cd823935324eb83a5b468b44/common/djangoapps/student/helpers.py#L614-L696) exist in openEdx for creating user account and profile that is utilized by [eox-core](https://github.com/eduNEXT/eox-core/blob/7850de3b9a84b493a67e375acfdc2e231237c333/eox_core/edxapp_wrapper/backends/users_h_v1.py#L97) but making it a separate end point would be helpful for other plugable apps.

 - [ ] [Deleting courses API](https://github.com/edx/edx-platform/blob/master/lms/djangoapps/dashboard/sysadmin.py#L383-L408)
     - [ ] `POST Params`: course_id.
     - [ ]  `Permissions`: Staff
     - [ ] `Unit testing`: 100% coverage
- [ ] [Importing courses (from git) API](https://github.com/edx/edx-platform/blob/master/lms/djangoapps/dashboard/git_import.py)
- [ ] [Gathering cross-course enrollment data](https://github.com/edx/edx-platform/blob/master/lms/djangoapps/dashboard/sysadmin.py#L419-L477) (TBD)
- [ ] [Git Lgos](https://github.com/edx/edx-platform/blob/master/lms/djangoapps/dashboard/sysadmin.py#L480-L563)
As per "Dave's" comment, If we want to store logs into app own storage instead of in mongo then I think, The git logs logic should be the part of SysAdmin django app but I am not sure what will be performance impact if we persist this data in django model. 

@pdpinch @HamzaIbnFarooq kindly take a look over it and let me know if anything I missed over here.

**Comment by pdpinch** [comment]
I copied this into Google doc because I had some questions that I think need further discussion: https://docs.google.com/document/d/1z6bmM5yHIY_yR8wLCStMQk3JlhAZDJj8XptMWoGmE0c/edit#heading=h.8ineo2m2ivpa

**Comment by briangrossman** [comment]
Phase I

- [x] : #190 - sysadmin dashboard - phase 1: Remove "Download list of all users" functionality
- [x] : #191 - sysadmin dashboard - phase 1: Address any python3 issues
- [x] : #192 - sysadmin dashboard - phase 1: deprecation message
- [x] : #193 - sysadmin dashboard - phase 1: remove "Check and repair external authentication map" button

**Comment by asadiqbal08** [comment]
**Phase 2:**
@pdpinch kindly take a look over these and share thoughts. 

- [x] [SysAdmin Django application](https://github.com/mitodl/edx-platform/issues/245)
- [x] [Showing SysAdmin in OpenEdx Navigation Bar](https://github.com/mitodl/edx-platform/issues/246)(OpenEdx PR)
- [x] [[SysAdmin] Create User Functionality](https://github.com/mitodl/edx-platform/issues/247)
- [x] [[SysAdmin] Delete Course Functionlity ](https://github.com/mitodl/edx-platform/issues/248)
- [x] [[SysAdmin] GitLogs Functionality](https://github.com/mitodl/edx-platform/issues/249)
- [x] [[SysAdmin] Remove the SysAdmin from OpenEdx](https://github.com/mitodl/edx-platform/issues/250)(OpenEdx PR)

**Comment by pdpinch** [comment]
Thanks @asadiqbal08. I reviewed the issues. I moved most of them to the new syadmin repo and made some edits and comments.

**Comment by pdpinch** [comment]
Wow, I think we can close this epic! 🎉 

Now all we have to is announce the sysadmin dashboard on the discuss.openedx.org
